name: test-workflow-dispatch
on:
  repository_dispatch:
    types: ["generate"]
  workflow_dispatch:
    inputs:
      generator-organization:
        description: 'Generator organization'
        required: true
        default: 'metronom-gmbh'
      generator-repository:
        description: 'Generator repository'
        required: true
        default: 'lpx-workflow-generator'
      generator-version:
        description: 'Generator tag/branch'
        required: true
        default: 'master'
      target-organization:
        description: 'Target organization'
        required: true
        default: 'developer-experience'
      target-repository:
        description: 'Target repository'
        required: true
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: greating
      run: | 
        echo "merge-bot is called with the following parameters"
        echo "generator to be used"
        echo "  generator.organization: ${{ github.event.client_payload.generator.organization }}"
        echo "  generator.repository:   ${{ github.event.client_payload.generator.repository }}"
        echo "  generator.version:      ${{ github.event.client_payload.generator.version }}"
        echo "target repository to which the pull request should be applied"
        echo "  target organization:    ${{ github.event.client_payload.organization }}"
        echo "  target repository:      ${{ github.event.client_payload.repository }}"
