name: test-workflow-dispatch
on:
  repository_dispatch:
    types: ["generate"]
  workflow_dispatch:
    inputs:
      generator-organization:
        description: 'Generator organization'
        required: true
        default: 'metronom-gmbh'
      generator-repository:
        description: 'Generator repository'
        required: true
        default: 'lpx-workflow-generator'
      generator-version:
        description: 'Generator tag/branch'
        required: true
        default: 'master'
      target-organization:
        description: 'Target organization'
        required: true
        default: 'developer-experience'
      target-repository:
        description: 'Target repository'
        required: true
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: greating
      run: | 
        if [[ ${{github.event.inputs.generator-repository}} ]];then
          echo "This workflow is triggered manually"
          echo "generator-organization: ${{ github.event.inputs.generator-organization }}"
          echo "generator-repository: ${{ github.event.inputs.generator-repository }}"
          echo "generator-version: ${{ github.event.inputs.generator-version }}"
          echo "target-organization: ${{ github.event.inputs.target-organization }}"
          echo "target-repository: ${{ github.event.inputs.target-repository }}"
          echo "::set-env name=generator-organization::${{ github.event.inputs.generator-organization }}"
          echo "::set-env name=generator-repository::${{ github.event.inputs.generator-repository }}"
          echo "::set-env name=generator-version::${{ github.event.inputs.generator-version }}"
          echo "::set-env name=target-organization::${{ github.event.inputs.target-organization }}"
          echo "::set-env name=target-repository::${{ github.event.inputs.target-repository }}"
        fi
        echo "merge-bot is called with the following parameters"
        echo "generator to be used"
        echo "  generator.organization: ${{ env.generator-organization }}"
        echo "  generator.repository:   ${{ env.generator-repository }}"
        echo "  generator.version:      ${{ env.generator-version }}"
        echo "target repository to which the pull request should be applied"
        echo "  target organization:    ${{ env.target-organization }}"
        echo "  target repository:      ${{ env.target-repository }}"
        #echo "merge-bot is called with the following parameters"
        #echo "generator to be used"
        #echo "  generator.organization: ${{ github.event.client_payload.generator.organization }}"
        #echo "  generator.repository:   ${{ github.event.client_payload.generator.repository }}"
        #echo "  generator.version:      ${{ github.event.client_payload.generator.version }}"
        #echo "target repository to which the pull request should be applied"
        #echo "  target organization:    ${{ github.event.client_payload.organization }}"
        #echo "  target repository:      ${{ github.event.client_payload.repository }}"
