name: Input processing
on:
  workflow_dispatch:
    inputs:
      name:
        description: A name
        required: true
        default: 'Uwe Daub'
      name_with_blanks:
        description: A name with leading and trailing blanks
        required: true
        default: ' Uwe Daub '

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - 
        id: compare_output
        run: |
          echo "'${{ github.event.inputs.name }}'"
          echo "'${{ github.event.inputs.name_with_blanks }}'"
          old = $(echo "${{ github.event.inputs.name_with_blanks }}")
          new = $(echo "${{ github.event.inputs.name_with_blanks }}" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
          echo "'$old'"
          echo "'$new'"
