name: Test Event Detection
on:
  workflow_dispatch:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo $EVENT
        env:
          EVENT: ${{ github.event_name }}
      - run: echo "Here event push"
        if: github.event_name == "push"
      - run: echo "Here event workflow_dispatch"
        if: github.event_name == "workflow_dispatch"
      - run: echo "Here event pull_request"
        if: github.event_name == "pull_request"
